<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\TransactionalOutbox.Infrastructure\TransactionalOutbox.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\TransactionalOutbox.Web\TransactionalOutbox.Web.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" PrivateAssets="all" />
    <PackageReference Include="xunit" PrivateAssets="all" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
